apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: salvadoruriel/clients-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: ENDPOINT
          value: "http://node-server-service:3041"
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3040
  externalIPs:
  - 140.112.16.173
    #our machine/server's ip
